name: macOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14  # Apple Silicon; zmień na macos-13 dla Intel
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies & build .app
        run: |
          python -m pip install -r requirements.txt pyinstaller
          pyinstaller -y --name "Tim Roy Performer Arp" --windowed --onedir \
            --icon TimRoy.icns \
            --add-data "config.json:." \
            --add-data "presets:presets" \
            --add-data "icons:icons" \
            main_app.py

      - name: Create DMG (drag & drop)
        run: |
          STAGE=dmg_stage
          APP="Tim Roy Performer Arp.app"
          rm -rf "$STAGE" TimRoyPerformerArp.dmg
          mkdir -p "$STAGE"
          cp -R "dist/$APP" "$STAGE/"
          ln -s /Applications "$STAGE/Applications"
          hdiutil create -volname "Tim Roy Performer Arp" -srcfolder "$STAGE" -ov -format UDZO TimRoyPerformerArp.dmg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS-release
          path: |
            "dist/Tim Roy Performer Arp.app"
            TimRoyPerformerArp.dmg 