name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies & convert icon
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller pillow
          python -c "from PIL import Image; Image.open('app-icon.png').convert('RGBA').save('app-icon.ico')"

      - name: Build executable
        run: |
          pyinstaller -y --name "Tim Roy Performer Arp" --windowed --onedir ^
            --icon app-icon.ico ^
            --add-data "config.json;." ^
            --add-data "presets;presets" ^
            --add-data "icons;icons" ^
            main_app.py

      - name: Install Inno Setup CLI
        run: choco install innosetup -y

      - name: Build installer
        run: iscc installer.iss

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-release
          path: |
            "dist/Tim Roy Performer Arp/**"
            TimRoyPerformerArp_Setup.exe 